config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts

  root :to => 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def index
  	@posts = Post.order('created_at DESC')
  end

  def show

    @post = Post.find(params[:id])

  end

  def edit

    @post = Post.find(params[:id])


  end

  def new
  	@post = Post.new
  end
  def create

  	 @post = Post.new(user_params)

    if @post.save

      redirect_to posts_path, :notice => "Your Post was saved!"
    
    else
      render "new"

    end

  end
  def update

    @post = Post.find(params[:id])
    if @post.update_attributes(user_params)
      redirect_to posts_path, :notice => "Your Post has been updated"
    else
      render "edit"
    end

  end

  def destroy

    @post = Post.find(params[:id])

    @post.destroy
    redirect_to posts_path

  end


 private
 	def user_params
  	  params.require(:post).permit(:title, :content)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Session3</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Blogger</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
         
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
               <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %> </li>
          <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, :class => "glyphicon glyphicon-user"%></li>
          <li><%= link_to "Login", new_user_session_path, :class => "glyphicon glyphicon-log-in"%></li>
          
          <%end%>
        </ul>
      </div>
    </nav>
  <body>
       

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit New Post</h1>
<hr>

<%= form_for @post do |f| %>
	<p>
		<%= f.label :title %></br>
		<%= f.text_field :title %>

	</p>
	<p>
		<%= f.label :content %></br>
		<%= f.text_area :content %>
		
	</p>
	<p>
		<%= f.submit "Edit a new Post" %></br>
		
		
	</p>



<% end %>

app/views/posts/index.html.erb
<div class="container">
	<h1>Posts</h1>
	<hr>



	<% @posts.each do |post| %>
		

		<h2><%= link_to post.title, post_path(post) %></h2>
		
		<small>Created at: <%= post.created_at %></small>

		<% if not post.content? %>
		 	<h4>No Content Added.</h4> 
		<% else %>
			<h4><%= post.content %></h4>
		<% end %>
		
		
		<hr>

	<% end %>

	<%= link_to "Add new Post", new_post_path %>
</div>

app/views/posts/new.html.erb
<h1>Add New Post</h1>
<hr>

<%= form_for @post do |f| %>
	<p>
		<%= f.label :title %></br>
		<%= f.text_field :title %>

	</p>
	<p>
		<%= f.label :content %></br>
		<%= f.text_area :content %>
		
	</p>
	<p>
		<%= f.submit "Add a new Post" %></br>
		
		
	</p>



<% end %>

app/views/posts/show.html.erb
<div class="container">
	<h1><%= @post.title %></h1>
	<small><%= @post.created_at %></small>
	<p><%= @post.content %></p>
	<%= link_to "Edit Post", edit_post_path(@post)%><br>
	<%= link_to "Delete Post", @post, :confirm => "Are You Sure?", :method => :delete %>
	<hr>

	<%= link_to "Back To HomePage", posts_path %>
</div>